@startuml
<style>
class {
    BackGroundColor lightblue
    LineColor black 
    FontColor black 
    HeaderFontStyle bold 
}
</style>

class "**TreasureFound_Fact**" as TreasureFound_Fact {
  **KEY SCD ATTRIBUTE**
  FK\t\tTreasureID
  FK\t\tDateID
  FK\t\tUserSK
  FK\t\tWeatherSK
  //\t\tTotalCachesFound//
  //\t\tDescriptionLength//
  //\t\tSearchTime//
}

note right of TreasureFound_Fact
Main TreasureFound Fact
Attributes:
TreasureID -> Foreign key to Treasure_Dim
LogID -> Foreign key to Log_Dim
UserSK -> Foreign key to User_Dim
WeatherSK -> Foreign key to Weather_Dim
SearchTime -> Time spent searching for the treasure
TotalCachesFound -> Total amount of caches found
DescriptionLength -> Length of the description for the treasure
end note

class "**Treasure_Dim**" as Treasure_Dim {
  **KEY SCD ATTRIBUTE**
  PK\t0\tTreasureID
  \t0\tTerrain
  \t0\tDifficulty
  \t0\tCity
  \t0\tCountryCode
  \t0\tContainerSize 
}

note left of Treasure_Dim 
Treasure Dimension
Attributes:
TreasureID -> Primary key
Terrain -> Enum describing the terrain type [0-> Flat, 1-> Hills etc.]
Difficulty -> Enum describing the dificulty [0-> Easy, 1-> Medium etc.] 
City -> City
CountryCode -> Code of the country that the treasure is located in
ContainerSize -> Size of the container
end note

class "**User_Dim**" as User_Dim {
  **KEY SCD ATTRIBUTE**
  PK\t2\tUserSK
  \t0\tUserID
  \t2\tCity
  //\t2\tDedicator//
  //\t2\tExperienceLevel// 
}

note right of User_Dim
User Dimension
Attributes:
UserSK -> Surrogate key
UserID -> ID of the user
City -> Home city of the user
Dedicator (new) -> Is user a dedicator or not?
ExperienceLevel (new) ->
  Enum [0-> Starter, 1-> Amateur, 2-> Professional, 3-> Pirate]
end note

class "**Date_Dim**" as Date_Dim {
  **KEY SCD ATTRIBUTE**
  PK\t0\tDateSK
  \t0\tDate
  //\t1\tDayofTheWeek//
  //\t1\tWeek//
  //\t1\tMonth//
  //\t1\tSeason//
}

note left of Date_Dim
Date Dimension
Attributes:
DateSK -> Surrogate key
Date -> Complete date
DayofTheWeek -> Monday, Tuesday etc.
Week -> Week of the year
Month -> January, February etc.
Season -> Winter, Spring etc.
end note

class "**Weather_Dim**" as Weather_Dim {
  **KEY SCD ATTRIBUTE**
  PK\t2\tWeatherSK
  //\t2\tRainfall//
}

note right of Weather_Dim
Weather Dimension
Attributes:
WeatherSK -> Surrogate key
Rainfall -> Amount of rain
end note

TreasureFound_Fact -up-> Treasure_Dim : "*" "1"
TreasureFound_Fact -down-> User_Dim : "*" "1"
TreasureFound_Fact -left-> Date_Dim : "1" "*"
TreasureFound_Fact -down-> Weather_Dim : "1" "*"

legend left
//Attributes in cursive// are not available in the catchem source system

**Additional analytical questions:**
Do users searching for treasures in their home city find them more often, on average, than users from different locations?
Do longer (more detailed) descriptions allow users to find treasure quicker, on average?
Does the amount of rainfall influence the likelihood of finding a treasure?
Does the size of the container influence the difficulty of found treasures?
end legend

@enduml

